# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"test": "00_core.ipynb",
         "another_test": "01_util.ipynb",
         "third_test": "01_util.ipynb"}

modules = ["core.py",
           "util.py"]

doc_url = "https://mengxr.github.io/nbdev_test/"

git_url = "https://github.com/mengxr/nbdev_test/tree/master/"

def custom_doc_links(name): return None
