# AUTOGENERATED! DO NOT EDIT! File to edit: 01_util.ipynb (unless otherwise specified).

__all__ = ['another_test']

# Cell
from .core import test

# Cell
def another_test():
    test()

# Cell
def _private():
    pass